[package]
name = "ironcraft"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Networking library for Minecraft: Java Edition servers and clients"
repository = "github.com/dec4234/ironcraft"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "5.0.0"
anyhow = "1.0.86"
tokio = {features = ["full"], version = "1.37.0"}
rayon = "1.10.0"
openssl = {version = "0.10.64", features = ["vendored"]}
serde_json = "1.0.117"
serde = {version = "1.0.202", features = ["derive"]}
uuid = {version = "1.8.0", features = ["v4"]}
zerocopy = {version = "0.7.29", features = ["derive", "byteorder"]}
bincode = {version = "2.0.0-rc.3", features = ["default", "serde"]}
base64 = "0.22.1"
error = "0.1.9"
indexmap = "2.2.6"
log = "0.4.21"
image = {version = "0.25.1", features = ["default", "png"]}
flate2 = {version = "1.0.30", features = ["zlib"]}
regex = "1.10.4"
fastsnbt = "0.2.0"
reqwest = "0.12.4"
sandstone-derive = {path = "sandstone-derive" }

[dev-dependencies]
#craftio-rs = "0.1.0"
#mcproto-rs = {version = "0.2.0", features = ["v1_15_2"]}