[package]
name = "ironcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
anyhow = "1.0.75"
tokio = {features = ["full"], version = "1.34.0"}
openssl = {version = "0.10.30", features = ["vendored"]}
serde_json = "1.0.59"
serde = {version = "1.0.193", features = ["derive"]}
uuid = "1.6.1"
zerocopy = {version = "0.7.29", features = ["derive"]}
hematite-nbt = "0.5.2"