[workspace]
members = [
    "sandstone",
    "examples/status_handler",
    "sandstone/src/sandstone-derive",
]
default-members = ["sandstone/", "examples/status_handler", "sandstone/src/sandstone-derive"]

[build.env]
passthrough = [
    "RUSTFLAGS",
    "RUST_BACKTRACE",
]