[package]
name = "ironcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
anyhow = "1.0.80"
tokio = {features = ["full"], version = "1.36.0"}
rayon = "1.9.0"
openssl = {version = "0.10.30", features = ["vendored"]}
serde_json = "1.0.114"
serde = {version = "1.0.197", features = ["derive"]}
uuid = "1.7.0"
zerocopy = {version = "0.7.29", features = ["derive"]}
quartz_nbt = "0.2.8"
bincode = {version = "2.0.0-rc.3", features = ["default", "serde"]}
base64 = "0.21.5"
#craftio-rs = "0.1.0"
#mcproto-rs = {version = "0.2.0", features = ["v1_15_2"]}
error = "0.1.9"
indexmap = "2.2.3"