[package]
name = "sandstone"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Networking library for Minecraft: Java Edition servers"
repository = "https://github.com/dec4234/sandstone"
homepage = "https://github.com/dec4234/sandstone"
readme = "../README.md"
keywords = ["minecraft", "networking", "server", "protocol"]
categories = ["network-programming", "game-development", "game-engines"]

exclude = ["src/sandstone-derive"]

[dependencies]
simple_logger = "5.0.0"
tokio = {features = ["full"], version = "1.37.0"}
rayon = "1.10.0"
openssl = {version = "0.10.64", features = ["vendored"]}
serde_json = "1.0.117"
serde = {version = "1.0.202", features = ["derive"]}
uuid = {version = "1.8.0", features = ["v4"]}
zerocopy = {version = "0.7.29", features = ["derive", "byteorder"]}
bincode = {version = "2.0.0-rc.3", features = ["default", "serde"]}
base64 = "0.22.1"
error = "0.1.9"
log = "0.4.21"
image = {version = "0.25.1", features = ["default", "png"]}
flate2 = {version = "1.0.30", features = ["zlib"]}
regex = "1.10.4"
fastsnbt = "0.2.0"
reqwest = "0.12.4"
sandstone-derive = "0.1.0"
thiserror = "1.0.61"

[dev-dependencies]
#craftio-rs = "0.1.0"
#mcproto-rs = {version = "0.2.0", features = ["v1_15_2"]}

[profile.dev]
opt-level = 3
overflow-checks = true
lto = true