[package]
name = "status_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
ironcraft = {path = "../../../ironcraft"}
tokio = {version = "1.37.0", features = ["full", "macros"]}
simple_logger = "5.0.0"
log = "0.4.21"
image = "0.25.1"